plugins:
  swiftlint:
    enabled: true
exclude_patterns: 
  - "Example-iOS/"
  - "Example-tvOS/"
  - "Tests/"
  - "Configs/"
  - "Carthage/"
  - "fastlane/"
  - ".codeclimate.yml"
  - ".jazzy.yaml"
  - ".swiftlint.yml"
  - ".travis.yml"
  - ".gitignore"
  - ".swift-version"
  - "LICENSE"
  - "*.md"
  - "*.podspec"
  - "*.xcodeproj"
  - "Cartfile"
  - "Cartfile.resolved"
  - "**/*.h"
  - "**/*.plist"
