included: # paths to include during linting. `--path` is ignored if present.
  - STLocationRequest

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Frameworks

disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
