branches:
  only:
    - master
    - develop
    - /^hotfix.*$/
    - /^feature.*$/

notifications:
  email:
    on_success: change
    on_failure: always

osx_image: xcode9
language: swift

before_install:
  - brew outdated xctool || brew upgrade xctool
  - carthage update

script:
  - fastlane test
  - pod lib lint