osx_image: xcode9
language: swift

before_install:
  - brew outdated xctool || brew upgrade xctool
  - carthage update

script:
  - xcodebuild -project "STLocationRequest.xcodeproj" -scheme "STLocationRequest" -sdk "iphonesimulator" | xcpretty -c
  - pod lib lint